FROM golang:alpine as builder
MAINTAINER Jack Murdock <jack_murdock@comcast.com>

WORKDIR /go/src/github.com/Comcast/codex-fenrir

RUN apk add --update git curl

COPY . .

RUN go build -o fenrir_linux_amd64

FROM alpine

RUN apk --no-cache add ca-certificates
RUN mkdir -p /etc/fenrir
VOLUME /etc/fenrir

EXPOSE 8080

COPY --from=builder /go/src/github.com/Comcast/codex-fenrir/fenrir_linux_amd64 /
COPY fenrir.yaml /
ENTRYPOINT ["/fenrir_linux_amd64"]